### ISSUE TITLE
The extension crashes upon install

### ISSUE THREAD

**Issue by zz0rk** [ybotspawn/Keep-ULauncher#15]
Installed gkeepapi
ulauncher_5.7.3_all.deb

Message: 'com.github.ybotspawn.keep-ulauncher'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.ybotspawn.keep-ulauncher'

```

**Comment by ybotspawn** [comment]
Sorry for the delay.  Looks like some changes may have been made to Ulauncher, since i Last updated the code.  I'll reproduce and identify the issue

**Comment by jpmorr** [comment]
Same error here. Any update?

Message: 'com.github.ybotspawn.keep-ulauncher'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.ybotspawn.keep-ulauncher'

```

**Comment by ybotspawn** [comment]
Sorry, need to find a system I can test it on as I recently switched to mac.  I'll try to get some traction on it this week.

**Comment by ybotspawn** [comment]
This looks like it might be related to the version of gkeepapi.   What python version did you use to install it?

**Comment by elkattan** [comment]
I have the same issue

### Error Details
Message: 'com.github.ybotspawn.keep-ulauncher'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.ybotspawn.keep-ulauncher'

```

Python Version: V3.9
ULauncher Version: V5.11
Extention API: V2.0
